stand-up

diff --git a/lib-prj b/lib-prj
--- a/lib-prj
+++ b/lib-prj
@@ -14,7 +14,7 @@ alias trace_prj='[ "$trace" == "1" ] && echo -e '
 	# psetadd
 	# psetdel
 	# psetren
-	# psetsw
+	# psw
 
 	# correct cmd_edit_host_config
 	# rename list to set in helps ??
@@ -24,7 +24,13 @@ alias trace_prj='[ "$trace" == "1" ] && echo -e '
 	# empty params -> help
 	# pmove to another list
 	# plist add help header
-	# show_sync_needed_status - both mode(pull/push)
+	# get_sync_status - both mode(pull/push)
+	# unite cmd_state_of_one_project cmd_state_of_all_projects
+	# unite save
+	# unite get
+	# unite sync
+	# unite fix with save
+	# ~ fix one/all
 
 	# support named params style: -v -h -n: -p: -l:(-s?) -m:"" 
 	# -n=<prj> -p=<path> -t=<type> -r=<remote> -l(s?)=<list(set?)>
@@ -55,7 +61,7 @@ alias trace_prj='[ "$trace" == "1" ] && echo -e '
 	# тильда в переменной для указания в пути домашней папки- крэшит команды (cd, ls ..)
 		# workaround: eval - http://stackoverflow.com/questions/11065077/eval-command-in-bash-and-its-typical-uses 
 		# re="~(.*)"; if [[ $path =~ $re ]]; then  path=${BASH_REMATCH[1]}; fi; cd $HOME$path
-	# to trace just set special var 'trace=1; <cmd>; trace=0'
+	# if you want edit lib-prj and then trace it, you can use next cmd: preload; trace=1; <cmd>; trace=0
 
 # install functions======================
 utils-prj-setup(){
@@ -77,7 +83,7 @@ utils-prj-uninstall(){
 	}
 
 # service functions======================
-get_default_project_list () { 	# [<list>]
+get_project_default_list () { 	# [<list>]
 	local project_list=$1
 	if [[ "$project_list" == "" ]]; then
 		project_list="$(eval cat "$utils_prj_configs/$utils_prj_the_host/default" | sed -E -n 's/^default_list=([^#]*)/\1/p' | tr -d '\r')"
@@ -85,14 +91,12 @@ get_default_project_list () { 	# [<list>]
 	echo "$project_list" # return value
 	}
 get_project_name_verified () { 	# <prj>
-	#local root=$1 #echo "root:$root"
 	local prj=$1
 	trace_prj "prj:\t\t$prj [get_project_name_verified]" 1>&2
-	#[[ "$root" == "" ]] && echo "[LIB: FIND PROJECT] root for project is missed !" 1>&2 && return
-	[[ "$prj" == "" ]] && echo "[LIB: FIND PROJECT] project name is missed !" 1>&2 && return
+	[[ "$prj" == "" ]] && echo "[get_project_name_verified] project name is missed !" 1>&2 && return
 	
 	( # to restore path after cd
-	cd "$utils_prj_configs/$utils_prj_the_host" #$root
+	cd "$utils_prj_configs/$utils_prj_the_host"
 	find_path="find" # linux/osx
 	[[ "$TERM" == "cygwin" ]] && find_path="$(cygpath-m "$EXEPATH")/usr/bin/find" # in windows $EXEPATH ex. C:\app\git - std env by git bash
 	#$(cygpath-m "$EXEPATH") or canonpath after correct
@@ -153,14 +157,19 @@ get_projectPath_findByName () {	# <prj>
 	  done
 	)
   }
-show_sync_needed_status(){	# <remote_mode>
-	# ex. show_sync_needed_status true # to compare with last commit from remote host
+get_sync_status(){	# <remote_mode>
+	# ex. get_sync_status true # to compare with last commit from remote host
 	# ??todo: return two out param ???  array?  or  pull/push/both/diverged only?
 	local use_remote_host=$1  	# true / false
-	local result_format=$2 		# when 'simple' then print yes/no else print msg for user 
+	local result_format=$2 		# when 'silent' then print yes/no else print msg for user 
+	[ "$3" != "" ] && local trace=$3
+
 	[ "$result_format" == "" ] && result_format=simple
 	[ "$use_remote_host" == "" ] && use_remote_host=false
-	trace_prj "result_format:\t\t$result_format [show_sync_needed_status]" 1>&2
+	[ "$use_remote_host" == "remote" ] && use_remote_host=true
+	trace_prj "use_remote_host:$use_remote_host [get_sync_status]" 1>&2
+	trace_prj "result_format:\t$result_format [get_sync_status]" 1>&2
+	#trace_prj $([ "$result_format" != "silent" ] && echo "notice mode [get_sync_status]") 1>&2
 	local LOCAL=$(git rev-parse @)
 	if [[ "$use_remote_host" == "true" ]]; then
 		local REMOTE=$(git ls-remote 2>/dev/null | awk "/HEAD/ {print \$1}")
@@ -170,34 +179,21 @@ show_sync_needed_status(){	# <remote_mode>
 	local BASE=$(git merge-base @ @{u})
 	#echo LOCAL:$LOCAL REMOTE:$REMOTE BASE:$BASE
 	if [ $LOCAL = $REMOTE ]; then
-	  	if [ "$result_format" == "simple" ]; then 
-	  		echo "ok" 
-	  	  # else true?
-	  	  fi
+		echo "ok" 
 	  elif [ $LOCAL = $BASE ]; then
-	  	if [ "$result_format" == "simple" ]; then 
-	  		echo "pull"
-	  	  else
-			echo -e "${yellow} NEED TO PULL !${norm}"
-		  fi
+	  	[ "$result_format" != "silent" ] && echo -e "${yellow} NEED TO PULL !${norm}" 1>&2
+	  	echo "pull"
 	  elif [ $REMOTE = $BASE ]; then
-	  	if [ "$result_format" == "simple" ]; then 
-	  		echo "push"
-	  	  else
-			echo -e "${yellow}NEED TO PUSH !${norm}" 
-		  fi
-		#true #echo "Need to push"
+	  	[ "$result_format" != "silent" ] && echo -e "${yellow}NEED TO PUSH !${norm}" 1>&2
+	  	echo "push"
 	  else
-	  	if [ "$result_format" == "simple" ]; then 
-	  		echo "diverged"
-	  	  else
-			echo -e "${red_bright} DIVERGED !!${norm}" # ! NEED TO PUSH AFTER
-		  fi
+	  	[ "$result_format" != "silent" ] && echo -e "${red_bright} DIVERGED !!${norm}" 1>&2 # ! NEED TO PUSH AFTER
+	  	echo "diverged"
 	  fi
 	}
 
 # config functions ======================
-cmd_edit_host_config(){		# ped	[<list>]
+cmd_edit_host_config(){		# peh	[<list>]
 	# ped [<list>]	
 	# edit default or specified repo list
 
@@ -215,11 +211,17 @@ cmd_edit_host_config(){		# ped	[<list>]
 
 	ed $repos
 	}
-cmd_list_projects(){		# plist	[<list>]
+cmd_edit_users_config(){	# peu
+	true
+	}
+cmd_show_current_config(){	# pshow
+	true
+	}
+cmd_enum_projects(){		# plist	[<list>]
 	# plist <list>
 	# echo utils_prj_the_host: $utils_prj_the_host
 	prj_list=$1
-	prj_list=$(get_default_project_list $prj_list)  # verify
+	prj_list=$(get_project_default_list $prj_list)  # verify
 	#echo REPO LIST: $repos
 	echo "========= $repos ========="
 
@@ -230,6 +232,9 @@ cmd_list_projects(){		# plist	[<list>]
 		echo -e "$prj_name:\t$path"
 		)
 	  done
+	}
+cmd_enum_sets(){		# psets
+	true
 	}
 cmd_add_project(){		# padd	<prj> [<list>] 
 	# cmd_add_project <prj> [<list>] 
@@ -247,7 +252,7 @@ cmd_add_project(){		# padd	<prj> [<list>]
 	[ "$trace" == "1" ] && echo -e "utils_prj_the_host:\t\t$utils_prj_the_host"
 
 	if [[ "$prj_list" == "" ]]; then
-		prj_list_default=$(get_default_project_list); [ "$trace" == "1" ] && echo -e "default_list:\t $prj_list_default"
+		prj_list_default=$(get_project_default_list); [ "$trace" == "1" ] && echo -e "default_list:\t $prj_list_default"
 		[ "$prj_list_default" == "" ] && echo -e "${red}[PROJECT ADD] prj_list_default not found !${norm}" && return
 		prj_list="$prj_list_default.list"
 	  else
@@ -309,7 +314,7 @@ cmd_move_project(){		# pmove	<prj>|. [<list>]
 	# echo utils_prj_the_host: $utils_prj_the_host
 
 	if [[ "$list" == "" ]]; then
-		prj_list=$(get_default_project_list).list 
+		prj_list=$(get_project_default_list).list 
 	  else
 	  	prj_list="$list.list"
 	  fi
@@ -341,7 +346,7 @@ cmd_rename_project(){		# ren 	<prj>
 	[ $trace -eq 1 ] && echo -e "utils_prj_the_host: $utils_prj_the_host"
 
 	if [[ "$list" == "" ]]; then
-		prj_list=$(get_default_project_list).list 
+		prj_list=$(get_project_default_list).list 
 	  else
 	  	prj_list="$list.list"
 	  fi
@@ -356,7 +361,7 @@ cmd_rename_project(){		# ren 	<prj>
 	#echo sed -i "s/^$curr_prj_name\$/$new_prj_name/g" "$utils_prj_configs/$utils_prj_the_host/$prj_list" ; return
 	mv "$utils_prj_configs/$utils_prj_the_host/$curr_prj_name" "$utils_prj_configs/$utils_prj_the_host/$new_prj_name" || return
 
-	sed -i -E "s/^$curr_prj_name\$/$new_prj_name/g" "$utils_prj_configs/$utils_prj_the_host/$prj_list" || return # sed -i "s/^jr$/jrhw/g" `echo $utils_prj_configs/$utils_prj_the_host/$(get_default_project_list).list`
+	sed -i -E "s/^$curr_prj_name\$/$new_prj_name/g" "$utils_prj_configs/$utils_prj_the_host/$prj_list" || return # sed -i "s/^jr$/jrhw/g" `echo $utils_prj_configs/$utils_prj_the_host/$(get_project_default_list).list`
 
 	#echo "path=$new_path" 	>  $prj_path
 	#echo "type=git" 	>> $prj_file
@@ -373,7 +378,12 @@ cmd_rename_project(){		# ren 	<prj>
 	# if $remote == "" then current
 	# if $set == "" then default
 	}
-#cmd_edit_host_config
+
+#psets
+#psetadd
+#psetdel
+#psetren
+#psetsw
 
 # navigate and state functions===========
 cmd_go_to_project_home(){	# pgo 	<prj> [<list>?] # dubl aliases?
@@ -390,7 +400,7 @@ cmd_go_to_project_home(){	# pgo 	<prj> [<list>?] # dubl aliases?
 
 	trace_prj "utils_prj_home:\t$utils_prj_home"
 	trace_prj "utils_prj_the_host: $utils_prj_the_host"
-		# repos=$1; repos=$(get_default_project_list $repos) # echo repos: $repos
+		# repos=$1; repos=$(get_project_default_list $repos) # echo repos: $repos
 	#echo path: "$utils_prj_configs/$utils_prj_the_host" 
 	#get_project_name_verified "$utils_prj_configs/$utils_prj_the_host" $project
 	prj_repo=$(get_project_name_verified $project) 
@@ -406,45 +416,44 @@ cmd_go_to_project_home(){	# pgo 	<prj> [<list>?] # dubl aliases?
 	[ "$ConEmuPID" != "" ] && $ConEmuBaseDir/ConEmuC -GuiMacro Rename 0 "${PWD##*/}" 1> /dev/null
 	[ "$TERM_PROGRAM" == "Apple_Terminal" ] && echo -ne "\033]0;${PWD##*/}\007"
 	}
-cmd_state_of_one_project(){	# pstate <prj>
+cmd_state_of_one_project(){	# pstate[x] <prj>
 	# pstate <prj>
 	prj=$1
+	[ "$remote_mode" == "" ] && remote_mode=false #$2
+
 	# echo home: $home
 	# echo utils_prj_the_host: $utils_prj_the_host
+	( # to return current path
 	if [[ "$prj" == "" ]]; then 
 		curr_path=`eval echo $(pwd)`; [ "$trace" == "1" ] && echo -e "cur_path:\t$curr_path"
-		prj_name=$(get_projectName_findByPath $curr_path); [ "$trace" == "1" ] && echo -e "prj_name:\t$prj_name"
+		prj_name=$(get_projectName_findByPath $curr_path dont_trace); [ "$trace" == "1" ] && echo -e "prj_name:\t$prj_name"
 		[[ "$prj_name" == "" ]] && echo "[SAVE PROJECT] project name is missed  and  not found by 'current path' in $utils_prj_configs/$utils_prj_the_host !" && return
-		# save prj
-		gis
-		show_sync_needed_status false
-		return
+	  else
+		# find prj file by current path
+		prj_path=$(get_projectPath_findByName $prj dont_trace) #"$utils_prj_configs/$utils_prj_the_host" 
+		# TODO: get prj vcs_type (svn, git)
+		echo -e "$prj:\t$prj_path"
+		eval cd "$prj_path"
 	  fi
-
-	# find prj file by current path
-	prj_path=$(get_projectPath_findByName $prj) #"$utils_prj_configs/$utils_prj_the_host" 
-	# TODO: get prj vcs_type (svn, git)
-	( # to return current path
-	echo -e "$prj:\t$prj_path"
-	eval cd "$prj_path"
 	gis
-	show_sync_needed_status false
+	sync_status=$(get_sync_status "$remote_mode" "notice" "notrace")
 	)
 	}
 cmd_state_of_all_projects(){	# pst[x] <list>|. 	# '.' for default list
 	local prj_list=$1
 	[ "$prj_list" == "" ] && prj_list=default
 	[ "$remote_mode" == "" ] && remote_mode=false #$2
-	[ "$trace" == "" ] && trace=0 #$3
+	[ "$trace" == "" ] && local trace=0 #$3
 	
 	trace_prj "utils_prj_home:\t\t$utils_prj_home"
 	trace_prj "utils_prj_the_host:\t$utils_prj_the_host"
 	trace_prj "remote_mode:\t\t$remote_mode"
 	
-	[[ "$prj_list" == "default" ]] && prj_list=$(get_default_project_list)
-	[ "$trace" == "1" ] && echo -e "prj_list:\t\ttrace$prj_list"
+	[[ "$prj_list" == "default" ]] && prj_list=$(get_project_default_list)
+	[ "$trace" == "1" ] && echo -e "prj_list:\t\t$prj_list"
 	#[[ "$remote_mode" == "" ]] && -e "${red}[lib-prj.:projects_state] 'remote_mode' param is not defined !${norm} " && return
 
+	echo
 	for prj in $(cat $utils_prj_configs/$utils_prj_the_host/$prj_list.list | sed -e /^$/d | tr -d '\r' | sort); do 
 		prj=`echo $prj` # normalize
 		prj_file=`echo $utils_prj_configs/$utils_prj_the_host/$prj`
@@ -455,28 +464,29 @@ cmd_state_of_all_projects(){	# pst[x] <list>|. 	# '.' for default list
 			continue
 		  fi
 
-		prj_file_norm=`eval echo $prj_file` #; echo prj_file_norm: $prj_file_norm
-		#echo sed -E -n 's/^path=([^#]+).*/\1/p' "$prj_file_norm"
-		#set -x
-		path=`sed -E -n 's/^path=([^#]+).*/\1/p' "$prj_file_norm" | tr -d '\r'` ;[ "$trace" == "1" ] && echo -e "path:\t\t\t$path"
-		#set +x
-		prj_path_norm=`eval echo $path` #; echo prj_path_norm: $prj_path_norm
-		[[ ! -d $prj_path_norm ]] && echo -e "${red} Project path '$path' not found !${norm} " && continue
+		#prj_file=`eval echo $prj_file` # cut <CR> 
+		trace_prj "prj_file:\t\t$prj_file" 
+
+		prj_path=`sed -E -n 's/^path=([^#]+).*/\1/p' "$prj_file" | tr -d '\r'` 
+		#prj_path=`eval echo $path` # cut <CR>
+		trace_prj "prj_path:\t\t$prj_path"
+
+		[[ ! -d $prj_path ]] && echo -e "${red} Project path '$prj_path' not found !${norm} " && continue
 		(
-		eval cd "$path"
+		eval cd "$prj_path"
 		changes=$(gis | wc -l) #; [ $trace -eq 1 ] && echo changes: $changes
-		#	echo -e "${grey}$prj: $path${norm}"
+		#	echo -e "${grey}$prj: $prj_path${norm}"
 		#  else
 
-		echo -e "\n ${grey_back} $prj_list  $prj \t $path ${norm}"
-		if [ $changes -ne 0 ]; then
-			git status -s --untracked-files
-		  fi
+		echo -e "${grey_back} $prj_list  $prj \t $prj_path ${norm}"
+		[ $changes -ne 0 ] && git status -s --untracked-files
 
-		sync_remote_status=$(show_sync_needed_status $remote_mode)
+		sync_remote_status=$(get_sync_status $remote_mode "notice" no_trace)
+		trace_prj "sync_remote_status:\t$sync_remote_status"
+		#[[ "$changes" != "0" || "$sync_remote_status" != "ok" ]] && 
+		echo
 		)
 	  done
-	echo
 	}
 
 # data sync =============================
@@ -491,7 +501,7 @@ cmd_save_one_projects(){	# psave <prj>|. [<msg>]
 	[ "$trace" == "1" ] && echo -e "prj:\t\t$prj"
 	# echo utils_prj_home: $utils_prj_home
 	# echo utils_prj_the_host: $utils_prj_the_host
-	#default_repos=$(get_default_project_list) 	# echo default_repos: $default_repos  # get default repos  
+	#default_repos=$(get_project_default_list) 	# echo default_repos: $default_repos  # get default repos  
 
 	if [[ "$prj" == "." ]]; then 
 		curr_path=`eval echo $(pwd)` #; echo cur_path:$curr_path
@@ -531,7 +541,7 @@ cmd_save_all_projects(){	# psavall <list>|. [<msg>]
 	[ "$trace" == "1" ] && echo -e "utils_prj_the_host:\t$utils_prj_the_host"
 
 	[[ "$list" == "." ]] && list="" # trik to save default
-	[[ "$list" == "" ]] && list=$(get_default_project_list)
+	[[ "$list" == "" ]] && list=$(get_project_default_list)
 	# echo list: $list  		# get default repos list
 
 	for prj in $(cat $utils_prj_configs/$utils_prj_the_host/$list.list | tr -d '\r' | sort); do 
@@ -557,7 +567,7 @@ cmd_save_one_project_at_local(){ # pfix <prj> <msg>
 	msg=$2
 
 	# echo utils_prj_the_host: $utils_prj_the_host
-	#default_repos=$(get_default_project_list) 	# echo default_repos: $default_repos  # get default repos  
+	#default_repos=$(get_project_default_list) 	# echo default_repos: $default_repos  # get default repos  
 
 	if [[ "$prj" == "" ]]; then 
 		curr_path=`eval echo $(pwd)` #; echo cur_path:$curr_path
@@ -581,6 +591,33 @@ cmd_save_one_project_at_local(){ # pfix <prj> <msg>
 	)
 
 	# TODO: test uncommited (untracked, changed, deleted, staged)
+	}
+cmd_save_all_projects_at_local(){ # pfixall <list>|. [<msg>]
+	# pfixall <prj> <msg> # add/commit
+	prj_list=$1
+	msg=$2
+
+	trace_prj "utils_prj_home:\t$utils_prj_home"
+	trace_prj "utils_prj_the_host:\t$utils_prj_the_host"
+
+	[[ "$prj_list" == "." ]] && prj_list="" # trik to save default
+	[[ "$prj_list" == "" ]] && prj_list=$(get_project_default_list)
+	trace_prj "prj_list:\t\t$prj_list"
+
+	for prj in $(cat $utils_prj_configs/$utils_prj_the_host/$prj_list.list | tr -d '\r' | sort); do 
+		prj_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $utils_prj_configs/$utils_prj_the_host/$prj | tr -d '\r'` # sed -E -n 's/^path=([^#]+)/\1/p' /Users/a.bysov/prj/utils-vcs/.cfg/ok/ue
+		(
+		eval cd "$prj_path"
+		changes=$(gis | wc -l)	# echo changes: $changes
+		echo -e "\n${grey_back} $prj_list  $prj \t $prj_path${norm} "
+		if [ $changes -ne 0 ]; then
+			gac "$msg" # TODO: переделать на использование либы 
+			echo
+		  fi
+		#${red}none${norm}"
+		)
+	  done
+	#echo
 	}
 cmd_pull_one_project(){		# pget 	<prj> 
 	# pget <prj> 
@@ -621,7 +658,7 @@ cmd_pull_all_projects(){	# pgetall <list>|.
 	# echo home: $home
 	# echo utils_prj_the_host: $utils_prj_the_host
 	[[ "$prj_list" == "." ]] && prj_list="" # trik to set default
-	[[ "$prj_list" == "" ]] && prj_list=$(get_default_project_list)
+	[[ "$prj_list" == "" ]] && prj_list=$(get_project_default_list)
 	trace_prj "prj_list:\t\t$prj_list" # get default repos list
 
 	for prj in $(cat $utils_prj_configs/$utils_prj_the_host/$prj_list.list | tr -d '\r' | sort ); do 
@@ -634,7 +671,7 @@ cmd_pull_all_projects(){	# pgetall <list>|.
 		trace_prj "changes:\t$changes" # 2> /dev/null 
 
 		if [ $changes -eq 0  -o  "$changes" == "" ]; then
-			compare_status=$(show_sync_needed_status)
+			compare_status=$(get_sync_status)
 			trace_prj "compare_status:\t$compare_status"
 			[ "$compare_status" == "diverged" ] && echo -e "${red_bright}DIVERGED ! NEED TO PUSH AFTER ${norm}" # 
 			if [ "$compare_status" == "pull" ]; then
