iMac-admin.local-up

diff --git a/lib-prj b/lib-prj
--- a/lib-prj
+++ b/lib-prj
@@ -15,10 +15,12 @@
 UTILS_PRJ_TRACE=0
 UTILS_PRJ_HOME=$(dirname ${BASH_SOURCE[0]})
 #UTILS_PRJ_CONFIGS=`eval echo $HOME/.utils-prj` # fix '~' bug
+UTILS_PRJ_CONFIGS=$HOME/.utils-prj
 UTILS_PRJ_THE_HOST=$(uname -n)
 UTILS_PRJ_THE_OS=$(uname -s)
 UTILS_PRJ_INCLUDE="utils-prj-include"
 UTILS_PRJ_ALIASES="utils-prj-aliases"
+
 case "$UTILS_PRJ_THE_OS" in
 	MINGW*)
 		UTILS_PRJ_SED_BACKUP="" #|MSYS*
@@ -40,6 +42,7 @@ case "$UTILS_PRJ_THE_OS" in
 	*)
 		# fail !
   esac
+
 alias log_print='[ "$UTILS_PRJ_TRACE" == "1" ] && echo -e 1>&2 '
 
 alias error='cmd_utils_prj_error'
@@ -130,29 +133,40 @@ cmd_utils_prj_wrapper(){
 # === install ===
 cmd_utils_prj_setup(){
 	# обновляем файлы если уже есть
-	[ ! -d ~/.utils-git ] && echo "to run commands on git repos required utils-git"
-	[ ! -d ~/.utils-env ] && echo "to get messages in colored manner required utils-env"
+	#[ ! -d ~/.utils-git ] && echo "to run commands on git repos required utils-git"
+	#[ ! -d ~/.utils-env ] && echo "to get messages in colored manner required utils-env"
 
 	[ ! -d "$HOME/.utils-prj" ] && mkdir "$HOME/.utils-prj"
-	[ ! -f "UTILS_PRJ_CONFIGS/$utils_include" ] && 	copy "$UTILS_PRJ_HOME/$UTILS_PRJ_INCLUDE" "UTILS_PRJ_CONFIGS/$UTILS_PRJ_INCLUDE"
-	# sed REPLACE path in 'export HOME_UTILS_PRJ= ex to "/C/app/utils-prj"
-	[ ! -f "UTILS_PRJ_CONFIGS/$UTILS_PRJ_ALIASES" ] && copy "$UTILS_PRJ_HOME/$UTILS_PRJ_ALIASES" "UTILS_PRJ_CONFIGS/$UTILS_PRJ_ALIASES"
-	# sed UTILS_PRJ_HOME in 'include' # to include lib to shell and some commands (ex. pel, p-help)
-	local bash_profile=`eval echo ~/.bash_profile` # fix ~ bug
+	[ ! -f "UTILS_PRJ_CONFIGS/$UTILS_PRJ_INCLUDE" ] && cp "$UTILS_PRJ_HOME/$UTILS_PRJ_INCLUDE" "$UTILS_PRJ_CONFIGS/$UTILS_PRJ_INCLUDE"
+	# REPLACE '$UTILS_ROOT' in 'export UTILS_PRJ_HOME="$UTILS_ROOT/utils-prj' to "$UTILS_PRJ_HOME"
+	sed -E -i 's|^(export UTILS_PRJ_HOME=")(\$UTILS_ROOT\/utils-prj)|\1'"$UTILS_PRJ_HOME"'|' "$UTILS_PRJ_CONFIGS/$UTILS_PRJ_INCLUDE"
+	[ ! -f "UTILS_PRJ_CONFIGS/$UTILS_PRJ_ALIASES" ] && cp "$UTILS_PRJ_HOME/$UTILS_PRJ_ALIASES" "$UTILS_PRJ_CONFIGS/$UTILS_PRJ_ALIASES"
+	local bash_profile=$HOME/.bash_profile # fix ~ bug
 	touch "$bash_profile"
-	# [ if not found '. ~/.utils-prj/include ] && echo '. ~/.utils-prj/include' >> .bash_profile
-	# echo "add to PATH?" read  [] echo "export PATH=$PATH:$UTILS_PRJ_HOME" >> $utils_include
+
+	# append include to .bash_profile
+	sed -E -n '/^\. "\$HOME\/\.utils-prj\/utils-prj-include"/{q111}' "$HOME/.bash_profile" #; echo $?
+	if [ "$?" != "111" ]; then
+		echo "" >> "$bash_profile"
+		echo '[[ $- == *i* ]] && echo "Loading $HOME/.utils-prj/utils-prj-include .. "' >> "$bash_profile"
+		echo '. "$HOME/.utils-prj/utils-prj-include"' >> "$bash_profile"
+	  fi
 	mkdir "$HOME/.utils-prj/$UTILS_PRJ_THE_HOST"
-	[ ! -f "UTILS_PRJ_CONFIGS/$UTILS_PRJ_THE_HOST/default" ] && copy "$UTILS_PRJ_HOME/default" "UTILS_PRJ_CONFIGS/$UTILS_PRJ_THE_HOST/default"
-	touch "UTILS_PRJ_CONFIGS/$UTILS_PRJ_THE_HOST/!projects"
-	echo "'p-help' - print readme.adoc"
+	if [ ! -f "UTILS_PRJ_CONFIGS/$UTILS_PRJ_THE_HOST/default" ];then
+		cp "$UTILS_PRJ_HOME/default" "$UTILS_PRJ_CONFIGS/$UTILS_PRJ_THE_HOST/default"
+		touch "$UTILS_PRJ_CONFIGS/$UTILS_PRJ_THE_HOST/-my_projects" # default set
+	  fi
+	notice "basic commands:"
 	echo "'pshow' - print current configuration (config files, project sets with projects)"
-	echo "'padd my_alias' - add alias and current folder to projects list (at start - 'default')"
-	echo "'plist' - review assigned aliases"
-	echo "'pgo my_alias' - cmd_project_go home"
-	echo "'pfix my_alias' - save project at local repository"
-	echo "'psave my_alias' - save project and sync with remote repository"
-	echo "'pget my_alias' - pull project from remote repository"
+	echo "'padd project_alias' - add alias and current folder to projects list (at start - 'default')"
+	echo "'plist' - review assigned aliases for current set"
+	echo "'pgo project_alias' - go home path for project"
+	echo "'pfix project_alias' - commit changes at local repository"
+	echo "'psave1 ' - save current project and sync with remote repository"
+	echo "'psave project_alias' - save any project and sync with remote repository"
+	echo "'pget project_alias' - pull project from remote repository"
+	echo "'psavea set_alias' - commit and push all projects for current context"
+	echo "'phelp' - commands overview"
 	}
 cmd_utils_prj_uninstall(){
 	# cut '. ~/.utils-prj/include' from .bash_profile
@@ -339,9 +353,9 @@ get_sync_status(){		# <remote_mode>
 
 # === config ===
 cmd_show_current_config(){	# pshow  green
-	echo -e "${red_on_green}  Overview:  ${norm}\nutils-prj - version 1.0\nUse 'p-help' for more\n"
+	echo -e "${red_on_green}  Overview:  ${norm}\nutils-prj - version 1.0\nUse 'phelp' for more\n"
 	echo -e "${red_on_green}  Where installed (\$UTILS_PRJ_HOME):  ${norm}\n$UTILS_PRJ_HOME/\n"
-	echo -e "${red_on_green}  How inited (position in $HOME/.bash_profile):  ${norm}\n$(grep -n -A 2 '.utils-prj' ~/.bash_profile)\n"
+	echo -e "${red_on_green}  .bash_profile lines :  ${norm}\n$(grep -n -A 2 -B 1 '.utils-prj' ~/.bash_profile)\n"
 	echo -e "${red_on_green}  Settings:  ${norm}\n$HOME/.utils-prj/$UTILS_PRJ_INCLUDE\n$HOME/.utils-prj/$UTILS_PRJ_ALIASES\n$HOME/.utils-prj/$UTILS_PRJ_THE_HOST/*"
 
 	cmd_project_enum ..
