ok-up

diff --git a/pren b/pren
--- a/pren
+++ b/pren
@@ -1,9 +1,9 @@
 #!/bin/bash
-# pren <prj> [<list>] 		# CASE #1 - rename prj name (find prj by curr_path)
-# pren <prj> [<list>] 		# CASE #2 - upd path of prj (find prj by name)
+# pren <prj> [<list>]  - rename prj name (alias) (find prj by curr_path)
 # pren -n=<prj> -p=<path> -t=<type> -r=<remote> -s=<set>
 
 new_prj_name=$1
+[[ "$new_prj_name" == "" ]] && echo -e "${red}[PROJECT RENAME] Project name not found !${norm}" && exit
 #list=$2
 
 #new_path=$(pwd) #; echo new_path: $new_path
@@ -24,21 +24,12 @@ if [[ "$list" == "" ]]; then
 # TODO: test prj in list
 #exit
 
-if [[ "$new_prj_name" == "" ]]; then
-	# CASE #1 - rename prj 
-	curr_prj_name=$(find_prj_by_path "$home/.cfg/$host" $curr_path) #; echo curr_prj_name: $curr_prj_name	 #old prj name
-	[[ $curr_prj_name == "" ]] && echo -e "${red}[PROJECT RENAME] Project file not found !${norm}" && exit
-	  #prj_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$new_prj_name | tr -d '\r'` #; echo curr_path: $prj_path
-	mv "$home/.cfg/$host/$curr_prj_name" "$home/.cfg/$host/$new_prj_name" || exit
-	  #echo "list: $home/.cfg/$host/$prj_list"
-	sed -i "s/^$curr_prj_name\$/$new_prj_name/g" "$home/.cfg/$host/$prj_list" || exit # sed -i "s/^jr$/jrhw/g" `echo $home/.cfg/$host/$(get_repos).list`
-  else
-	# CASE #2 - replace path
-	curr_prj_name=prj_name
-	# prj_file=$home/.cfg/$host/$new_prj_name
-	# [[ ! -f $prj_file ]] && echo "[PROJECT RENAME] Project is absent" && exit
-  fi
-
+curr_prj_name=$(find_prj_by_path "$home/.cfg/$host" $curr_path) #; echo curr_prj_name: $curr_prj_name	 #old prj name
+[[ "$curr_prj_name" == "" ]] && echo -e "${red}[PROJECT RENAME] Project file not found !${norm}" && exit
+  #prj_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$new_prj_name | tr -d '\r'` #; echo curr_path: $prj_path
+mv "$home/.cfg/$host/$curr_prj_name" "$home/.cfg/$host/$new_prj_name" || exit
+  #echo "list: $home/.cfg/$host/$prj_list"
+sed -i "s/^$curr_prj_name\$/$new_prj_name/g" "$home/.cfg/$host/$prj_list" || exit # sed -i "s/^jr$/jrhw/g" `echo $home/.cfg/$host/$(get_repos).list`
 
 #echo "path=$new_path" 	>  $prj_path
 #echo "type=git" 	>> $prj_file
